# Generated by Django 3.0.4 on 2020-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
